version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: tamtin_mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: TamTin@2026
      MONGO_INITDB_DATABASE: tamtin_db
    ports:
      - "27018:27017" # Map từ 27018 (máy chủ) vào 27017 (container)
    volumes:
      - mongodb_data:/data/db
    networks:
      - tamtin_network

  backend:
    image: ${DOCKERHUB_USERNAME:-trolevan26299}/tamtin-backend:latest
    container_name: tamtin-api
    restart: unless-stopped
    environment:
      - PORT=3001
      - DB_URI=mongodb://admin:TamTin%402026@mongodb:27017/tamtin_db?authSource=admin
      # Lưu ý: Sửa lại hostname mongodb thành 'mongodb' thay vì 'localhost' để gọi trong mạng docker
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
    networks:
      - tamtin_network

  frontend:
    image: ${DOCKERHUB_USERNAME:-trolevan26299}/tamtin-frontend:latest
    container_name: tamtin-web
    restart: unless-stopped
    ports:
      - "3000:80" # Chạy public ở cổng 3000 (map vào 80 nginx) hoặc có thể mở "80:80"
    depends_on:
      - backend
    networks:
      - tamtin_network

volumes:
  mongodb_data:
    name: tamtin_mongodb_data

networks:
  tamtin_network:
    name: tamtin_network
    driver: bridge
